### ISSUE TITLE
有线网口貌似有问题

### ISSUE THREAD

**Issue by jmluang** [HowieHye/Dell-7460-Hackintosh-OC#1]
非常感谢，就是有线似乎有点问题，你这边正常吗？

**Comment by yechao0518** [comment]
我的网卡更换成dw1820a 所以有部分配置做了修改 ，现在我的有线网络测试没有问题






-------- 原始信息 --------
发件人： orqzsf1 <notifications@github.com>
日期: 2020/9/2 17:23 (GMT+08:00)
收件人： HowieHye/Dell-7460-Hackintosh-OC <Dell-7460-Hackintosh-OC@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主题： [HowieHye/Dell-7460-Hackintosh-OC] 有线网口貌似有问题 (#1)


非常感谢，就是有线似乎有点问题，你这边正常吗？

―

**Comment by RainHuih** [comment]
我的是正常的，你可以换2.2.2版本的驱动，应该就可以了

**Comment by jmluang** [comment]
吐了，网线问题。。
