### ISSUE TITLE
食用方法以及常见问题

### ISSUE THREAD

**Issue by RainHuih** [HowieHye/Dell-7460-Hackintosh-OC#2]
[黑苹果安装指北手册](https://howiehye.top/post/9ff9620/)

**Comment by SimonZHH-314** [comment]
facetime和imessage激活不了

**Comment by MRJxing** [comment]
聚焦功能智能搜索到文件，应用程序什么的显示不出来是什么问题呢

**Comment by RainHuih** [comment]
> 聚焦功能智能搜索到文件，应用程序什么的显示不出来是什么问题呢
    这应该和EFI没关系吧
