### ISSUE TITLE
有线网卡有问题

### ISSUE THREAD

**Issue by hackerboygn** [HowieHye/Dell-7460-Hackintosh-OC#3]
我和#1 有同样的问题，有线网卡无法使用，表现为网线未插入，已排除网线的问题，因为切换回Windows下工作正常，原来用Clover也是好的。
![Jietu20200905-025427](https://user-images.githubusercontent.com/13834950/92322941-29b13b00-f067-11ea-87d4-6fb10aa16188.jpg)
![Jietu20200905-025304](https://user-images.githubusercontent.com/13834950/92322942-2b7afe80-f067-11ea-9804-44627e535286.jpg)
![Jietu20200905-024627](https://user-images.githubusercontent.com/13834950/92322943-2c139500-f067-11ea-8a6f-810672ae3f9b.jpg)
![Jietu20200905-024250](https://user-images.githubusercontent.com/13834950/92322944-2d44c200-f067-11ea-92d3-3417949e8bcb.jpg)
![Jietu20200905-024129](https://user-images.githubusercontent.com/13834950/92322945-2d44c200-f067-11ea-8ad3-1b2d24505bcf.jpg)

**Comment by hackerboygn** [comment]
经过测试发现，开机BIOS自检阶段对端的交换机Link灯是亮的，到白苹果进度条走一半时Link灯就灭了

**Comment by RainHuih** [comment]
切换回2.2.2版本的驱动

**Comment by hackerboygn** [comment]
2.2.2正常，同时我找到了2.3.0的解决方法：
系统偏好设置->网络->以太网->高级->硬件->配置：手动 | 速度：【选个正确的】 | 双工：【按需选择】

**Comment by hexiaoyanh** [comment]
same problem

**Comment by RainHuih** [comment]
> same problem
see @hackerboygn 's comment
