### ISSUE TITLE
博主真乃神人！

### ISSUE THREAD

**Issue by newham** [HowieHye/Dell-7460-Hackintosh-OC#6]
我的电脑是lenovo yoga710 CPU也是 7500u，自己弄了好半天EFI都不成功，用你的一开始也不行，今天看你提交了新代码，我又试了一下，居然可以了！
非常感谢博主，向你学习！

**Comment by RainHuih** [comment]
谢谢谢谢

**Comment by newham** [comment]
经过一些微调，基本上也已经完美了！ 
替换usbports.kext 为 usbinjectall.kext，wifi和蓝牙都正常了！
现在唯独一个缺陷是【关于本机】cpu显示不对，应该显示i7，但是却是i5...
请问博主有什么办法修改？
![iShot2020-11-16 16 40 14](https://user-images.githubusercontent.com/24582826/99231000-f8a17380-282a-11eb-810d-273a46383ed7.png)

**Comment by RainHuih** [comment]
http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1873200&highlight=CPU%2B%CF%D4%CA%BE

**Comment by newham** [comment]
已经解决！通过删除ProcessorType
![image](https://user-images.githubusercontent.com/24582826/99237550-99942c80-2833-11eb-8e3a-08ebc876d09f.png)
然后启动时先选择CleanNvram
再启动即可
![image](https://user-images.githubusercontent.com/24582826/99238901-44f1b100-2835-11eb-8606-347ba3082798.png)

**Comment by newham** [comment]
共享精神值得传承！我将我yoga710的EFI也上传到了github：[https://github.com/newham/yoga710-7500u-oc-bigsur](https://github.com/newham/yoga710-7500u-oc-bigsur)
再次感谢博主！

**Comment by RainHuih** [comment]
你可以提交到兵叔的[Hackintosh黑苹果长期维护机型EFI及安装教程整理](https://github.com/daliansky/Hackintosh)
