### ISSUE TITLE
有时候开机会卡住

### ISSUE THREAD

**Issue by jmluang** [HowieHye/Dell-7460-Hackintosh-OC#7]
首先感谢老哥的EFI，已升级11.0.1，但是有时候开机或者重启的时候，偶尔会会在白苹果的时候卡住

各位有同样的情况吗？

**Comment by jmluang** [comment]
感觉可能是网卡的问题，之前也遇到过，我的网卡是1560

**Comment by RainHuih** [comment]
之前我遇到过卡住的情况，我这边感觉是VoodooI2C驱动的问题，你可以换低版本试一试，我回头再看看
