### ISSUE TITLE
0.64 big sur 好用。谢谢楼主。有个bug，休眠之后再起来，触摸板会失效。没有接鼠标的时候，没有测试过接鼠标的状况。

### ISSUE THREAD

**Issue by suyuanhua** [HowieHye/Dell-7460-Hackintosh-OC#8]
0.64 big sur 好用。谢谢楼主。有个bug，休眠之后再起来，触摸板会失效。没有接鼠标的时候，没有测试过接鼠标的状况。
我试过，好多次，休眠时间特别短可能不会，时间几分钟以上再次唤醒一定会出现“丢失”触摸板。🙏

**Comment by RainHuih** [comment]
suyuanhua
        等我考完试看看什么情况 


2020-12-14
在2020年12月14日 21:53，suyuanhua<notifications@github.com> 写道：

0.64 big sur 好用。谢谢楼主。有个bug，休眠之后再起来，触摸板会失效。没有接鼠标的时候，没有测试过接鼠标的状况。
我试过，好多次，休眠时间特别短可能不会，时间几分钟以上再次唤醒一定会出现“丢失”触摸板。🙏

**Comment by suyuanhua** [comment]
> suyuanhua 等我考完试看看什么情况 2020-12-14 在2020年12月14日 21:53，suyuanhua<notifications@github.com> 写道： 0.64 big sur 好用。谢谢楼主。有个bug，休眠之后再起来，触摸板会失效。没有接鼠标的时候，没有测试过接鼠标的状况。 我试过，好多次，休眠时间特别短可能不会，时间几分钟以上再次唤醒一定会出现“丢失”触摸板。🙏 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

留心了一下：按触摸板唤醒是正常的；按电源键唤醒，则触摸板是“丢失”的。祝楼主考试门门💯！😄

**Comment by RainHuih** [comment]
今天看了一下，没有遇到这种情况啊
